POST http://localhost:5000/api/analyze
Content-Type: application/json

{
"source_ip": "192.168.1.10",
"destination_ip": "8.8.8.8",
"protocol": "TCP",

"service": "http",
"flag": "SF",

"duration": 12,
"src_bytes": 5000,
"dst_bytes": 3000
}

###


# curl -v -X POST http://127.0.0.1:5000/api/analyze
#-H "Content-Type: application/json"
#-d '{ "destination_ip":"192.168.1.16", "source_ip":"192.168.2.14", "duration":5.0, "protocol":"tcp", "service":"other", "flag":"SF", "src_bytes":0, "dst_bytes":0, "count":200, "srv_count":200, "serror_rate":0.95, "dst_host_count":180 }'
POST http://127.0.0.1:5000/api/analyze
Content-Type: application/json

{
  "destination_ip": "192.168.1.16",
  "source_ip": "192.168.2.14",
  "duration": 5.0,
  "protocol": "tcp",
  "service": "other",
  "flag": "SF",
  "src_bytes": 0,
  "dst_bytes": 0,
  "count": 200,
  "srv_count": 200,
  "serror_rate": 0.95,
  "dst_host_count": 180
}

###
